using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Windows.Forms;
using OSGeo.FDO.Schema;
using OSGeo.FDO.Connections;

namespace FdoToolbox.Core.Forms
{
    public partial class DataPropertyDefinitionDlg : Form
    {
        private IConnection _BoundConnection;

        internal DataPropertyDefinitionDlg(IConnection conn)
        {
            InitializeComponent();
            _BoundConnection = conn;
            _Definition = new DataPropertyDefinition(txtName.Text, txtDescription.Text);
            
            //Toggle UI based on capabilities
            cmbDataType.DataSource = _BoundConnection.SchemaCapabilities.DataTypes;
            chkNullable.Enabled = _BoundConnection.SchemaCapabilities.SupportsNullValueConstraints;
            chkAutoGenerated.Enabled = _BoundConnection.SchemaCapabilities.SupportsAutoIdGeneration;
            txtDefault.Enabled = _BoundConnection.SchemaCapabilities.SupportsDefaultValue;

            if(_BoundConnection.SchemaCapabilities.get_NameSizeLimit(OSGeo.FDO.Connections.Capabilities.SchemaElementNameType.SchemaElementNameType_Property) > 0)
                txtName.MaxLength = _BoundConnection.SchemaCapabilities.get_NameSizeLimit(OSGeo.FDO.Connections.Capabilities.SchemaElementNameType.SchemaElementNameType_Property);
            
            if(_BoundConnection.SchemaCapabilities.get_NameSizeLimit(OSGeo.FDO.Connections.Capabilities.SchemaElementNameType.SchemaElementNameType_Description) > 0)
                txtDescription.MaxLength = _BoundConnection.SchemaCapabilities.get_NameSizeLimit(OSGeo.FDO.Connections.Capabilities.SchemaElementNameType.SchemaElementNameType_Description);

            if(_BoundConnection.SchemaCapabilities.MaximumDecimalPrecision > 0)
                numPrecision.Maximum = _BoundConnection.SchemaCapabilities.MaximumDecimalPrecision;
            
            if(_BoundConnection.SchemaCapabilities.MaximumDecimalScale > 0)
                numScale.Maximum = _BoundConnection.SchemaCapabilities.MaximumDecimalScale;
        }

        internal DataPropertyDefinitionDlg(DataPropertyDefinition def, IConnection conn) : this(conn)
        {
            _Definition = def;
            txtName.Text = _Definition.Name;
            txtDescription.Text = _Definition.Description;
            txtDefault.Text = _Definition.DefaultValue;
            cmbDataType.SelectedItem = _Definition.DataType;
            chkAutoGenerated.Checked = _Definition.IsAutoGenerated;
            chkNullable.Checked = _Definition.Nullable;
            chkReadOnly.Checked = _Definition.ReadOnly;
            chkSystem.Checked = _Definition.IsSystem;
            numLength.Value = Convert.ToDecimal(_Definition.Length);
            numPrecision.Value = Convert.ToDecimal(_Definition.Precision);
            numScale.Value = Convert.ToDecimal(_Definition.Scale);
        }

        private DataPropertyDefinition _Definition;

        public static DataPropertyDefinition NewDataProperty(IConnection conn)
        {
            DataPropertyDefinitionDlg dlg = new DataPropertyDefinitionDlg(conn);
            if (dlg.ShowDialog() == DialogResult.OK)
            {
                return dlg._Definition;
            }
            return null;
        }

        public static void EditDataProperty(DataPropertyDefinition def, IConnection conn)
        {
            DataPropertyDefinitionDlg dlg = new DataPropertyDefinitionDlg(def, conn);
            dlg.ShowDialog();
        }

        private void btnOK_Click(object sender, EventArgs e)
        {
            //Set the class
            _Definition.Name = txtName.Text;
            _Definition.Description = txtDescription.Text;
            _Definition.IsAutoGenerated = chkAutoGenerated.Checked;
            _Definition.IsSystem = chkSystem.Checked;
            _Definition.Nullable = chkNullable.Checked;
            _Definition.ReadOnly = chkReadOnly.Checked;
            _Definition.DataType = (DataType)cmbDataType.SelectedItem;
            _Definition.DefaultValue = txtDefault.Text;
            _Definition.Scale = Convert.ToInt32(numScale.Value);
            _Definition.Precision = Convert.ToInt32(numPrecision.Value);
            _Definition.Length = Convert.ToInt32(numLength.Value);
            this.DialogResult = DialogResult.OK;
        }

        private void btnCancel_Click(object sender, EventArgs e)
        {
            this.DialogResult = DialogResult.Cancel;
        }

        private void chkAutoGenerated_CheckedChanged(object sender, EventArgs e)
        {
            if (chkAutoGenerated.Checked)
            {
                DataType dtype = (DataType)(cmbDataType.SelectedItem);
                if (Array.IndexOf<DataType>(_BoundConnection.SchemaCapabilities.SupportedAutoGeneratedTypes, dtype) < 0)
                {
                    AppConsole.Alert("Error", "This data type does not support auto-generation");
                    chkAutoGenerated.Checked = false;
                }
                else
                {
                    chkReadOnly.Checked = true;
                    chkNullable.Checked = false;
                }
            }
        }

        private void chkReadOnly_CheckedChanged(object sender, EventArgs e)
        {
            if (!chkReadOnly.Checked && chkAutoGenerated.Checked)
            {
                AppConsole.Alert("", "An auto-generated proeprty must be read-only");
                chkReadOnly.Checked = true;
            }
        }

        private void chkNullable_CheckedChanged(object sender, EventArgs e)
        {
            if (chkNullable.Checked && chkAutoGenerated.Checked)
            {
                AppConsole.Alert("", "An auto-generated property cannot be nullable");
                chkNullable.Checked = false;
            }
        }

        private void cmbDataType_SelectedIndexChanged(object sender, EventArgs e)
        {
            numLength.Maximum = (_BoundConnection.SchemaCapabilities.get_MaximumDataValueLength((DataType)cmbDataType.SelectedItem) > 0) 
                ? _BoundConnection.SchemaCapabilities.get_MaximumDataValueLength((DataType)cmbDataType.SelectedItem) 
                : 0;
        }
    }
}