//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FdoToolbox.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FdoToolbox.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap accept {
            get {
                object obj = ResourceManager.GetObject("accept", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application uses the following libraries:
        ///
        ///- Feature Data Objects (c) Autodesk/OSGeo (http://fdo.osgeo.org)
        ///- DockPanel Suite (c) Weifen Luo (http://sourceforge.net/projects/dockpanelsuite)
        ///- famfamfam silk icon set (c) Mark James (http://www.famfamfam.com/lab/icons/silk/)
        ///
        ///This application and its components are licensed under the GNU Lesser General Public Licence (see http://www.gnu.org/licenses/lgpl.html).
        /// </summary>
        internal static string APP_ABOUT {
            get {
                return ResourceManager.GetString("APP_ABOUT", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap application_edit {
            get {
                object obj = ResourceManager.GetObject("application_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_go {
            get {
                object obj = ResourceManager.GetObject("application_go", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_right {
            get {
                object obj = ResourceManager.GetObject("arrow_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bricks {
            get {
                object obj = ResourceManager.GetObject("bricks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;BulkCopyTask name=&quot;{0}&quot;&gt;
        ///	&lt;Source&gt;
        ///		&lt;Provider&gt;{1}&lt;/Provider&gt;
        ///		&lt;ConnectionString&gt;{2}&lt;/ConnectionString&gt;
        ///		&lt;Schema&gt;{3}&lt;/Schema&gt;
        ///	&lt;/Source&gt;
        ///	&lt;Target&gt;
        ///		&lt;Provider&gt;{4}&lt;/Provider&gt;
        ///		&lt;ConnectionString&gt;{5}&lt;/ConnectionString&gt;
        ///		&lt;Schema&gt;{6}&lt;/Schema&gt;
        ///	&lt;/Target&gt;
        ///	&lt;ClassMappings&gt;
        ///		{7}
        ///	&lt;/ClassMappings&gt;
        ///	&lt;BulkCopyOptions&gt;
        ///		&lt;CopySpatialContexts&gt;{8}&lt;/CopySpatialContexts&gt;
        ///		&lt;CoerceDataTypes&gt;{9}&lt;/CoerceDataTypes&gt;
        ///	&lt;/BulkCopyOptions&gt;
        ///&lt;/BulkCopyTask&gt;.
        /// </summary>
        internal static string BulkCopyTask {
            get {
                return ResourceManager.GetString("BulkCopyTask", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap chart_organisation {
            get {
                object obj = ResourceManager.GetObject("chart_organisation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chart_organisation_add {
            get {
                object obj = ResourceManager.GetObject("chart_organisation_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chart_organisation_delete {
            get {
                object obj = ResourceManager.GetObject("chart_organisation_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Mapping&gt;
        ///	&lt;DeleteTarget&gt;{0}&lt;/DeleteTarget&gt;
        ///	&lt;SourceClass&gt;{1}&lt;/SourceClass&gt;
        ///	&lt;TargetClass&gt;{2}&lt;/TargetClass&gt;
        ///	&lt;Properties&gt;
        ///		{3}
        ///	&lt;/Properties&gt;
        ///&lt;/Mapping&gt;.
        /// </summary>
        internal static string ClassMapping {
            get {
                return ResourceManager.GetString("ClassMapping", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap cross {
            get {
                object obj = ResourceManager.GetObject("cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap database {
            get {
                object obj = ResourceManager.GetObject("database", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap database_add {
            get {
                object obj = ResourceManager.GetObject("database_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap database_connect {
            get {
                object obj = ResourceManager.GetObject("database_connect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap database_table {
            get {
                object obj = ResourceManager.GetObject("database_table", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap disk {
            get {
                object obj = ResourceManager.GetObject("disk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap image {
            get {
                object obj = ResourceManager.GetObject("image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap information {
            get {
                object obj = ResourceManager.GetObject("information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap key {
            get {
                object obj = ResourceManager.GetObject("key", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap map {
            get {
                object obj = ResourceManager.GetObject("map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!-- 
        ///Menu definition file. 
        ///
        ///Edit this file to customise the application menu.
        ///
        ///Commands that don&apos;t exist or cannot be executed from the user interface 
        ///won&apos;t be shown in the menu.
        ///
        ///DO NOT DELETE THIS FILE!!!
        ///--&gt;
        ///&lt;MenuMap&gt;
        ///	&lt;Menu name=&quot;File&quot;&gt;
        ///		&lt;Command name=&quot;connect&quot; /&gt;
        ///		&lt;Command name=&quot;mkdstore&quot; /&gt;
        ///		&lt;Separator/&gt;
        ///		&lt;Command name=&quot;quit&quot; /&gt;
        ///	&lt;/Menu&gt;
        ///	&lt;Menu name=&quot;Tools&quot;&gt;
        ///		&lt;SubMenu name=&quot;FDO&quot;&gt;
        ///			&lt;Command name=&quot;regprovider&quot; /&gt;
        ///			&lt;Command name=&quot;un [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MenuMap {
            get {
                return ResourceManager.GetString("MenuMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!-- 
        ///Object Explorer menu definition file. 
        ///
        ///Edit this file to customise the Object Explorer menus.
        ///
        ///Commands that don&apos;t exist or cannot be executed from the user interface 
        ///won&apos;t be shown in the menu.
        ///
        ///DO NOT DELETE THIS FILE!!!
        ///--&gt;
        ///&lt;ObjectExplorer&gt;
        ///	&lt;Toolbar&gt;
        ///		&lt;Menu name=&quot;New&quot; resource=&quot;page_white&quot;&gt;
        ///			&lt;SubMenu name=&quot;Connection&quot; resource=&quot;database_connect&quot;&gt;
        ///				&lt;Command name=&quot;sdfconnect&quot; displayName=&quot;SDF&quot; /&gt;
        ///				&lt;Command name=&quot;shpconnect&quot; displayNa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OEMenuMap {
            get {
                return ResourceManager.GetString("OEMenuMap", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap package {
            get {
                object obj = ResourceManager.GetObject("package", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap page_refresh {
            get {
                object obj = ResourceManager.GetObject("page_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap page_white {
            get {
                object obj = ResourceManager.GetObject("page_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap page_white_code {
            get {
                object obj = ResourceManager.GetObject("page_white_code", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap plugin {
            get {
                object obj = ResourceManager.GetObject("plugin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap plugin_delete {
            get {
                object obj = ResourceManager.GetObject("plugin_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PropertyMapping&gt;
        ///	&lt;SourceProperty&gt;{0}&lt;/SourceProperty&gt;
        ///	&lt;TargetProperty&gt;{1}&lt;/TargetProperty&gt;
        ///&lt;/PropertyMapping&gt;.
        /// </summary>
        internal static string PropertyMapping {
            get {
                return ResourceManager.GetString("PropertyMapping", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap shape_handles {
            get {
                object obj = ResourceManager.GetObject("shape_handles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table {
            get {
                object obj = ResourceManager.GetObject("table", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table_add {
            get {
                object obj = ResourceManager.GetObject("table_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table_delete {
            get {
                object obj = ResourceManager.GetObject("table_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table_edit {
            get {
                object obj = ResourceManager.GetObject("table_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table_go {
            get {
                object obj = ResourceManager.GetObject("table_go", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table_relationship {
            get {
                object obj = ResourceManager.GetObject("table_relationship", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom {
            get {
                object obj = ResourceManager.GetObject("zoom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
