#define user_introduction 30
#define connecting_via_the_generic_dialog 230
#define connecting_via_express_dialogs 240
#define savingloading_connections 250
#define connection_notes 260
#define object_explorer_introduction 270
#define customising_context_menus 280
#define extending_the_object_explorer 290
#define schema_introduction 300
#define creating_new_classes 310
#define updating_existing_classes 320
#define notes 330
#define using_the_generic_dialog 340
#define creating_flat_files 350
#define preview_introduction 360
#define standard_query 370
#define aggregate_query 380
#define sql_query 390
#define saving_query_results 400
#define adding_new_features 410
#define creating_bulk_copy_tasks 420
#define express_bulk_copy_tasks 430
#define savingloading_bulk_copy_tasks 440
#define join_introduction 450
#define creating_database_joins 460
#define savingloading_join_tasks 470
#define cmd_introduction 140
#define UsingFdoUtil.exe 150
#define UsingFdoInfo.exe 160
#define UsingFdoQuery.exe 170
#define ErrorCodes 180
#define Architecture 200
#define CreatingExtensionModules 210
#define APIDocumentation 220

