using System;
using System.Collections.Generic;
using System.Text;

namespace FdoToolbox.Core.Utility
{
    public class FdoMetaDataNames
    {
        public const string FDO_IDENTITY_PROPERTY = "FDO_IDENTITY_PROPERTY";
        public const string FDO_AUTOGENERATED = "FDO_AUTOGENERATED";
        public const string FDO_GEOMETRY_PROPERTY = "FDO_GEOMETRY_PROPERTY";
        public const string FDO_GEOMETRY_PROPERTY_TYPE = "FDO_GEOMETRY_PROPERTY_TYPE";
        public const string FDO_GEOMETRY_PROPERTY_HAS_ELEVATION = "FDO_GEOMETRY_PROPERTY_HAS_ELEVATION";
        public const string FDO_GEOMETRY_PROPERTY_HAS_MEASURE = "FDO_GEOMETRY_PROPERTY_HAS_MEASURE";
        public const string FDO_GEOMETRY_PROPERTY_READONLY = "FDO_GEOMETRY_PROPERTY_READONLY";
    }
}
