#region LGPL Header
// Copyright (C) 2008, Jackie Ng
// http://code.google.com/p/fdotoolbox, jumpinjackie@gmail.com
// 
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
// 
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
// 
#endregion
using System;
using System.Collections.Generic;
using System.Text;

namespace FdoToolbox.Core.Utility
{
    public class FdoMetaDataNames
    {
        public const string FDO_IDENTITY_PROPERTY = "FDO_IDENTITY_PROPERTY";
        public const string FDO_AUTOGENERATED = "FDO_AUTOGENERATED";
        public const string FDO_GEOMETRY_PROPERTY = "FDO_GEOMETRY_PROPERTY";
        public const string FDO_GEOMETRY_PROPERTY_TYPE = "FDO_GEOMETRY_PROPERTY_TYPE";
        public const string FDO_GEOMETRY_PROPERTY_HAS_ELEVATION = "FDO_GEOMETRY_PROPERTY_HAS_ELEVATION";
        public const string FDO_GEOMETRY_PROPERTY_HAS_MEASURE = "FDO_GEOMETRY_PROPERTY_HAS_MEASURE";
        public const string FDO_GEOMETRY_PROPERTY_READONLY = "FDO_GEOMETRY_PROPERTY_READONLY";
    }
}
