using System;
using System.Collections.Generic;
using System.Text;

namespace FdoToolbox.Core.Feature
{
    public enum CapabilityType
    {
        // Command Capabilities

        FdoCapabilityType_CommandList,
        FdoCapabilityType_SupportsParameters,
        FdoCapabilityType_SupportsCommandTimeout,
        FdoCapabilityType_SupportsSelectExpressions,
        FdoCapabilityType_SupportsSelectFunctions,
        FdoCapabilityType_SupportsSelectDistinct,
        FdoCapabilityType_SupportsSelectOrdering,
        FdoCapabilityType_SupportsSelectGrouping,

        // Connection Capabilities

        FdoCapabilityType_ThreadCapability,
        FdoCapabilityType_SpatialContextTypes,
        FdoCapabilityType_LockTypes,
        FdoCapabilityType_SupportsConnectionTimeout,
        FdoCapabilityType_SupportsLocking,
        FdoCapabilityType_SupportsTransactions,
        FdoCapabilityType_SupportsLongTransactions,
        FdoCapabilityType_SupportsSQL,
        FdoCapabilityType_SupportsConfiguration,
        FdoCapabilityType_SupportsMultipleSpatialContexts,
        FdoCapabilityType_SupportsCSysWKTFromCSysName,
        FdoCapabilityType_SupportsWrite,
        FdoCapabilityType_SupportsMultiUserWrite,
        FdoCapabilityType_SupportsFlush,

        // Expression Capabilities

        FdoCapabilityType_ExpressionTypes,
        FdoCapabilityType_ExpressionFunctions,

        // Filter Capabilities

        FdoCapabilityType_ConditionTypes,
        FdoCapabilityType_SpatialOperations,
        FdoCapabilityType_DistanceOperations,
        FdoCapabilityType_SupportsGeodesicDistance,
        FdoCapabilityType_SupportsNonLiteralGeometricOperations,

        // Geometry Capabilities

        FdoCapabilityType_GeometryTypes,
        FdoCapabilityType_GeometryComponentTypes,
        FdoCapabilityType_Dimensionalities,
        FdoCapabilityType_CSSupportsArcs,

        // Raster Capabilities

        FdoCapabilityType_SupportsRaster,
        FdoCapabilityType_SupportsStitching,
        FdoCapabilityType_SupportsSubsampling,
        FdoCapabilityType_SupportsDataModel,

        // Schema Capabilities

        FdoCapabilityType_ClassTypes,
        FdoCapabilityType_DataTypes,
        FdoCapabilityType_SupportedAutoGeneratedTypes,
        FdoCapabilityType_SupportedIdentityPropertyTypes,
        FdoCapabilityType_MaximumDataValueLength_String,
        FdoCapabilityType_MaximumDataValueLength_BLOB,
        FdoCapabilityType_MaximumDataValueLength_CLOB,
        FdoCapabilityType_MaximumDataValueLength_Decimal,
        FdoCapabilityType_MaximumDataValueLength_Boolean,
        FdoCapabilityType_MaximumDataValueLength_Byte,
        FdoCapabilityType_MaximumDataValueLength_DateTime,
        FdoCapabilityType_MaximumDataValueLength_Double,
        FdoCapabilityType_MaximumDataValueLength_Int16,
        FdoCapabilityType_MaximumDataValueLength_Int32,
        FdoCapabilityType_MaximumDataValueLength_Int64,
        FdoCapabilityType_MaximumDataValueLength_Single,
        FdoCapabilityType_MaximumDecimalPrecision,
        FdoCapabilityType_MaximumDecimalScale,
        FdoCapabilityType_NameSizeLimit_Datastore,
        FdoCapabilityType_NameSizeLimit_Schema,
        FdoCapabilityType_NameSizeLimit_Class,
        FdoCapabilityType_NameSizeLimit_Property,
        FdoCapabilityType_NameSizeLimit_Description,
        FdoCapabilityType_ReservedCharactersForName,
        FdoCapabilityType_SupportsAssociationProperties,
        FdoCapabilityType_SupportsAutoIdGeneration,
        FdoCapabilityType_SupportsCalculatedProperties,
        FdoCapabilityType_SupportsCompositeId,
        FdoCapabilityType_SupportsCompositeUniqueValueConstraints,
        FdoCapabilityType_SupportsDataStoreScopeUniqueIdGeneration,
        FdoCapabilityType_SupportsDefaultValue,
        FdoCapabilityType_SupportsExclusiveValueRangeConstraints,
        FdoCapabilityType_SupportsInclusiveValueRangeConstraints,
        FdoCapabilityType_SupportsInheritance,
        FdoCapabilityType_SupportsMultipleSchemas,
        FdoCapabilityType_SupportsNetworkModel,
        FdoCapabilityType_SupportsNullValueConstraints,
        FdoCapabilityType_SupportsObjectProperties,
        FdoCapabilityType_SupportsSchemaModification,
        FdoCapabilityType_SupportsSchemaOverrides,
        FdoCapabilityType_SupportsUniqueValueConstraints,
        FdoCapabilityType_SupportsValueConstraintsList,
        FdoCapabilityType_SupportsWritableIdentityProperties,

    }  //  enum FdoCapabilityType
}
