#region LGPL Header
// Copyright (C) 2008, Jackie Ng
// http://code.google.com/p/fdotoolbox, jumpinjackie@gmail.com
// 
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
// 
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
// 
#endregion
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Windows.Forms;
using OSGeo.FDO.Schema;
using OSGeo.FDO.Connections;
using FdoToolbox.Core.Controls;
using FdoToolbox.Core.ClientServices;
using FdoToolbox.Core.Common;

namespace FdoToolbox.Core.Forms
{
    public partial class DataPropertyDefinitionDlg : Form
    {
        private SpatialConnectionInfo _BoundConnection;

        internal DataPropertyDefinitionDlg(SpatialConnectionInfo conn)
        {
            InitializeComponent();
            _BoundConnection = conn;
            _Definition = new DataPropertyDefinition(txtName.Text, txtDescription.Text);
            
            //Toggle UI based on capabilities
            ToggleUI();
        }

        private void ToggleUI()
        {
            cmbDataType.DataSource = this.BoundConnection.Connection.SchemaCapabilities.DataTypes;
            chkNullable.Enabled = this.BoundConnection.Connection.SchemaCapabilities.SupportsNullValueConstraints;
            chkAutoGenerated.Enabled = this.BoundConnection.Connection.SchemaCapabilities.SupportsAutoIdGeneration;
            txtDefault.Enabled = this.BoundConnection.Connection.SchemaCapabilities.SupportsDefaultValue;

            if (this.BoundConnection.Connection.SchemaCapabilities.get_NameSizeLimit(OSGeo.FDO.Connections.Capabilities.SchemaElementNameType.SchemaElementNameType_Property) > 0)
                txtName.MaxLength = this.BoundConnection.Connection.SchemaCapabilities.get_NameSizeLimit(OSGeo.FDO.Connections.Capabilities.SchemaElementNameType.SchemaElementNameType_Property);

            if (this.BoundConnection.Connection.SchemaCapabilities.get_NameSizeLimit(OSGeo.FDO.Connections.Capabilities.SchemaElementNameType.SchemaElementNameType_Description) > 0)
                txtDescription.MaxLength = this.BoundConnection.Connection.SchemaCapabilities.get_NameSizeLimit(OSGeo.FDO.Connections.Capabilities.SchemaElementNameType.SchemaElementNameType_Description);

            if (this.BoundConnection.Connection.SchemaCapabilities.MaximumDecimalPrecision > 0)
                numPrecision.Maximum = this.BoundConnection.Connection.SchemaCapabilities.MaximumDecimalPrecision;

            if (this.BoundConnection.Connection.SchemaCapabilities.MaximumDecimalScale > 0)
                numScale.Maximum = this.BoundConnection.Connection.SchemaCapabilities.MaximumDecimalScale;
        }

        internal DataPropertyDefinitionDlg(DataPropertyDefinition def, SpatialConnectionInfo conn) : this(conn)
        {
            _Definition = def;
            txtName.Text = _Definition.Name;
            txtDescription.Text = _Definition.Description;
            txtDefault.Text = _Definition.DefaultValue;
            cmbDataType.SelectedItem = _Definition.DataType;
            chkAutoGenerated.Checked = _Definition.IsAutoGenerated;
            chkNullable.Checked = _Definition.Nullable;
            chkReadOnly.Checked = _Definition.ReadOnly;
            chkSystem.Checked = _Definition.IsSystem;
            numLength.Value = Convert.ToDecimal(_Definition.Length);
            numPrecision.Value = Convert.ToDecimal(_Definition.Precision);
            numScale.Value = Convert.ToDecimal(_Definition.Scale);
        }

        private DataPropertyDefinition _Definition;

        public static DataPropertyDefinition NewDataProperty(SpatialConnectionInfo conn)
        {
            DataPropertyDefinitionDlg dlg = new DataPropertyDefinitionDlg(conn);
            if (dlg.ShowDialog() == DialogResult.OK)
            {
                return dlg._Definition;
            }
            return null;
        }

        public static void EditDataProperty(DataPropertyDefinition def, SpatialConnectionInfo conn)
        {
            DataPropertyDefinitionDlg dlg = new DataPropertyDefinitionDlg(def, conn);
            dlg.ShowDialog();
        }

        private void btnOK_Click(object sender, EventArgs e)
        {
            errorProvider.Clear();
            if (string.IsNullOrEmpty(txtName.Text))
            {
                errorProvider.SetError(txtName, "Required");
                return;
            }
            
            DataType dtype = (DataType)cmbDataType.SelectedItem;
            if (dtype == DataType.DataType_BLOB ||
                dtype == DataType.DataType_CLOB ||
                dtype == DataType.DataType_String)
            {
                if (numLength.Value == 0)
                {
                    errorProvider.SetError(numLength, "Zero-length string, BLOB or CLOB");
                    return;
                }
            }
            else if (dtype == DataType.DataType_Decimal)
            {
                //Check zero length precision/scale
                if (numPrecision.Value == 0)
                {
                    errorProvider.SetError(numPrecision, "Zero precision");
                    return;
                }
                if (numScale.Value == 0)
                {
                    errorProvider.SetError(numScale, "Zero scale");
                    return;
                }
            }

            //Set the class
            _Definition.Name = txtName.Text;
            _Definition.Description = txtDescription.Text;
            _Definition.IsAutoGenerated = chkAutoGenerated.Checked;
            _Definition.IsSystem = chkSystem.Checked;
            _Definition.Nullable = chkNullable.Checked;
            _Definition.ReadOnly = chkReadOnly.Checked;
            _Definition.DataType = dtype;
            _Definition.DefaultValue = txtDefault.Text;
            _Definition.Scale = Convert.ToInt32(numScale.Value);
            _Definition.Precision = Convert.ToInt32(numPrecision.Value);
            _Definition.Length = Convert.ToInt32(numLength.Value);
            this.DialogResult = DialogResult.OK;
        }

        private void btnCancel_Click(object sender, EventArgs e)
        {
            this.DialogResult = DialogResult.Cancel;
        }

        private void chkAutoGenerated_CheckedChanged(object sender, EventArgs e)
        {
            if (chkAutoGenerated.Checked)
            {
                DataType dtype = (DataType)(cmbDataType.SelectedItem);
                if (Array.IndexOf<DataType>(this.BoundConnection.Connection.SchemaCapabilities.SupportedAutoGeneratedTypes, dtype) < 0)
                {
                    AppConsole.Alert("Error", "This data type does not support auto-generation");
                    chkAutoGenerated.Checked = false;
                }
                else
                {
                    chkReadOnly.Checked = true;
                    chkNullable.Checked = false;
                }
            }
        }

        private void chkReadOnly_CheckedChanged(object sender, EventArgs e)
        {
            if (!chkReadOnly.Checked && chkAutoGenerated.Checked)
            {
                AppConsole.Alert("", "An auto-generated proeprty must be read-only");
                chkReadOnly.Checked = true;
            }
        }

        private void chkNullable_CheckedChanged(object sender, EventArgs e)
        {
            if (chkNullable.Checked && chkAutoGenerated.Checked)
            {
                AppConsole.Alert("", "An auto-generated property cannot be nullable");
                chkNullable.Checked = false;
            }
        }

        private void cmbDataType_SelectedIndexChanged(object sender, EventArgs e)
        {
            DataType dtype = (DataType)(cmbDataType.SelectedItem);
            long max = this.BoundConnection.Connection.SchemaCapabilities.get_MaximumDataValueLength(dtype);
            numLength.Maximum = (max < 0) ? long.MaxValue : max;
        }

        public SpatialConnectionInfo BoundConnection
        {
            get { return _BoundConnection; }
        }


        public void SetName(string name)
        {
            this.BoundConnection.Name = name;
        }
    }
}